from enum import Enum

class COMPUTE_PROCESSOR_TYPES(Enum):
    # CPU Processors
    CASCADE_LAKE = 'Cascade Lake'
    SKYLAKE = 'Skylake'
    HASWELL = 'Haswell'
    BROADWELL = 'Broadwell'
    COFFEE_LAKE = 'Coffee Lake'
    SANDY_BRIDGE = 'Sandy Bridge'
    IVY_BRIDGE = 'Ivy Bridge'
    ICELAKE = 'Ice Lake'
    AMD_EPYC_1ST_GEN = 'AMD EPYC 1st Gen'
    AMD_EPYC_2ND_GEN = 'AMD EPYC_2nd Gen'
    AMD_EPYC_3RD_GEN = 'AMD EPYC_3rd Gen'
    AWS_GRAVITON = 'AWS Graviton'
    AWS_GRAVITON_2 = 'AWS Graviton2'
    # GPU Processors
    NVIDIA_K520 = 'Nvidia K520'
    NVIDIA_A10G = 'Nvidia A10G'
    NVIDIA_T4 = 'Nvidia T4'
    NVIDIA_TESLA_M60 = 'Nvidia Tesla M60'
    NVIDIA_TESLA_K80 = 'Nvidia Tesla K80'
    NVIDIA_TESLA_V100 = 'Nvidia Tesla V100'
    NVIDIA_TESLA_A100 = 'Nvidia Tesla A100'
    NVIDIA_TESLA_P4 = 'Nvidia Tesla P4'
    NVIDIA_TESLA_P40 = 'Nvidia Tesla P40'
    NVIDIA_TESLA_P100 = 'Nvidia Tesla P100'
    AMD_RADEON_PRO_V520 = 'AMD Radeon Pro V520'
    XILINX_ALVEO_U250 = 'Xilinx Alveo U250'
    # Unknown
    UNKNOWN = 'Unknown'

cascadeLakeSkylake = [
    COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE,
    COMPUTE_PROCESSOR_TYPES.SKYLAKE,
]

broadwellHaswell = [
    COMPUTE_PROCESSOR_TYPES.HASWELL,
    COMPUTE_PROCESSOR_TYPES.BROADWELL,
]

broadwellSkylake = [
    COMPUTE_PROCESSOR_TYPES.BROADWELL,
    COMPUTE_PROCESSOR_TYPES.SKYLAKE,
]

broadwelCascadeLake = [
    COMPUTE_PROCESSOR_TYPES.BROADWELL,
    COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE,
]

cascadeLakeSkylakeBroadwellHaswell = [
    COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE,
    COMPUTE_PROCESSOR_TYPES.SKYLAKE,
    COMPUTE_PROCESSOR_TYPES.BROADWELL,
    COMPUTE_PROCESSOR_TYPES.HASWELL,
]

cascadeLakeSkylakeBroadwell = [
    COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE,
    COMPUTE_PROCESSOR_TYPES.SKYLAKE,
    COMPUTE_PROCESSOR_TYPES.BROADWELL,
]

cascadeLakeHaswell = [
    COMPUTE_PROCESSOR_TYPES.HASWELL,
    COMPUTE_PROCESSOR_TYPES.CASCADE_LAKE,
]

skyLakeBroadwellHaswellAMDRome = [
    COMPUTE_PROCESSOR_TYPES.SKYLAKE,
    COMPUTE_PROCESSOR_TYPES.BROADWELL,
    COMPUTE_PROCESSOR_TYPES.HASWELL,
    COMPUTE_PROCESSOR_TYPES.AMD_EPYC_2ND_GEN,
]

skyLakeBroadwellHaswellSandyBridgeIvyBridge = [
    COMPUTE_PROCESSOR_TYPES.SKYLAKE,
    COMPUTE_PROCESSOR_TYPES.BROADWELL,
    COMPUTE_PROCESSOR_TYPES.HASWELL,
    COMPUTE_PROCESSOR_TYPES.SANDY_BRIDGE,
    COMPUTE_PROCESSOR_TYPES.IVY_BRIDGE,
]
