# Constants for different usage types and units in cloud services
MEMORY_USAGE_TYPES = ['RAM', 'Ram', 'Memory']
UNKNOWN_USAGE_UNITS = ['requests']
UNKNOWN_USAGE_TYPES = [
    'Dedicated Memcache',
    'BigQuery BI Engine',
    'AutoML Tables Deployment',
    'Local Disk Time Dataprep',
    'Shuffle Time',
    'Snapshots message backlog',
    'Subscriptions message backlog',
    'Subscriptions retained acknowledged messages',
    'Cloud SQL: Backups',
    'Publisher Throughput Capacity',
    'Subscriber Throughput Capacity',
    'Server node',
    'Backend Instances',
    'Frontend Instances',
    'Server Node',
    'Analysis Slots Attribution',
    'Build time',
    'Dataprep Unit',
    'IP address',
    'usage - hour',
    'D2',
    'D4',
    'Policy Charge',
    'Endpoint Charge',
    'NAT Gateway',
    'Action Time',
    'Billing Adjustment',
    'Filestore Capacity Premium',
    'Filestore Capacity Standard',
    'Pod mCPU Requests',
    'Pod Memory Requests',
    'Pod Ephemeral Storage Requests',
]
UNSUPPORTED_USAGE_TYPES = [
    'Fee',
    'fee',
    'Billing',
    'Reattribution',
    'Cache Fill',
    'External IP Charge',
    'Static Ip',
    'Vpn Tunnel',
    'Service Charge',
]
UNKNOWN_SERVICE_TYPES = [
    'Cloud DNS',
    'Cloud Key Management Service',
    'Cloud Machine Learning Engine',
    'Cloud Spanner',
    'Cloud Speech API',
    'SendGrid',
    'Support',
    'Secret Manager',
    'Cloud Build',
    'Cloud Run',
    'Cloud Data Fusion',
    'Cloud Dialogflow API',
    'Cloud Natural Language',
    'BigQuery Data Transfer Service',
    'BigQuery Reservation API',
    'Cloud AutoML',
    'Cloud Test Lab',
    'Cloud TPU',
    'Cloud Video Intelligence API',
    'Cloud Vision API',
    'Container Builder',
    'Firebase Test Lab',
    'Security Command Center',
    'Stackdriver',
]
SERVICES_TO_OVERRIDE_USAGE_UNIT_AS_UNKNOWN = [
    'Secret Manager',
    'Cloud Key Management Service',
]
COMPUTE_STRING_FORMATS = [
    'Core',
    'CORE',
    'VCPU',
    'vCPU',
    'CPU',
    'CPUs',
    'Kubernetes Clusters',
    'GPU',
    'DCU',
]
NETWORKING_STRING_FORMATS = [
    'Egress',
    'egress',
    'data delivery',
    'network traffic',
    'Download',
]

# Constants for grouping query results by date types in GCP queries
GCP_QUERY_GROUP_BY = {
    'day': 'DAY',
    'week': 'ISOWEEK',
    'month': 'MONTH',
    'quarter': 'QUARTER',
    'year': 'YEAR',
}
